version: "3.9"

services:
  postgres:
    image: postgres:13.5
    container_name: "postgres"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_URL: "${DB_URL}"
    ports:
      - ${POSTGRES_PORT}:5432
  redis:
    image: redis:6.0.16
    container_name: "redis"
    environment:
      CACHE_URL: "${CACHE_URL}"
    hostname: redis
    ports:
      - ${REDIS_PORT}:6379
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    environment:
      BUS_URL: "${BUS_URL}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    ports:
      - ${RABBITMQ_PORT}:5672
